### ISSUE TITLE
Move CEO and DataExplorer to Platform

### ISSUE THREAD

**Issue by ischolten** [influxdata/platform#1038]
### workers

- [x] add workers (https://github.com/influxdata/platform/issues/1095)
- [ ] ability to create worker jobs
- [ ] executing queries as a worker job
- [ ] convert transformation functions to worker jobs

### basic properties

- [x] view name and rename
- [x] time range and set
- [x] visualization type and change
- [x] initial vis options panel for choosing graph type

### visualizations

- [x] LineView properties and update - axes, colors, legend
- [x] render line view
- [x] render step plot view
- [x] render stacked view
- [ ] render bar chart view
- [ ] render single stat view
- [ ] render gauge view
- [ ] render line + ss view
- [ ] markdown properties and update - type
- [ ] render markdown
- [ ] TableView properties and update - tableOptions, fieldOptions, decimalPlaces, timeFormat
- [ ] render table view

### display options 

- [x] changing visualization types in redux ([#172](https://github.com/influxdata/applications-team-issues/issues/172))
- [ ] render line graph display options - (https://github.com/influxdata/platform/pull/1352)
- [ ] render single stat/ gauge display options
- [ ] render table display options
- [ ] render notes 

### query builder

- [ ] store and update query type (flux vs influxql)
- [ ] sources dropdown 
- [ ] dynamic source

### flux

- [ ] Render flux only if flux is query type selected
- [ ] Render script editor 
- [ ] submit script executes script
- [ ] render wizard 
- [ ] render flux schema explorer
- [ ] render flux functions panel
  
### influxql

- [ ] render influxql only if influxql is query type selected
- [ ] Render tabs  
- [ ] add and delete tabs
- [ ] render query text editor in each tab
- [ ] submit query executes query
- [ ] render influxql schema explorer
- [ ] clicks modify the script
- [ ] script modifies the schema explorer

### extra time machine 

- [ ] raw data view
- [ ] download csv
- [ ] autorefresh

### data explorer 

- [x] create DE page with icon
- [x] renders the same time machine as veo
- [ ] local storage
- [ ] query params
- [ ] send to dashboard

### dashboards

- [ ] export dashboard
- [ ] import dashboard
- [ ] template variables

**Comment by russorat** [comment]
this is handled by many smaller issues
