### ISSUE TITLE
Implement DROP BUCKET

### ISSUE THREAD

**Issue by e-dard** [influxdata/platform#1837]
This is a meta issue covering all the things we need to do to implement a performant `DROP BUCKET` feature.

Until we rework how we store TSM data on disk, multiple buckets can physically share TSM files. This makes enforcing retention periods, or dropping an entire bucket relatively expensive. In both cases they require a range-based delete, and can result in the creation of many tombstone entries for high cardinality data.

From a storage perspective, we need to expose an API that allows the API tier to provide a bucket and org name, which, when called, will apply an appropriate delete command to the `FileStore`, `Cache` and `WAL`.

```go 
func (e *Engine) DeleteBucket(orgID, bucketID platform.ID) error {
    ...
}
```

 As part of this work, we need to consider dealing with the following:

  - [ ] Expose `DeleteBucket` API in `storage.Engine`.
  - [x] Currentlly, tombstones are applied during startup, so that TSM data that has been deleted is not queryable. This process is expensive, and is causing performance issues when scaled out to dropping entire an buckets' worth of TSM data. We need to improve how tombstones are applied. This work will be tracked in #https://github.com/influxdata/platform/issues/1595
  - [x] In Platform, *all* series keys are prefixed with a measurement comprising an org and bucket id. Therefore, dropping a bucket involves deleting all series keys sharing the same prefix. Rather than creating tombstone entries for each and every key, we could create a new prefix-based tombstone entry, for a set of keys belonging to the same prefix. This work is tracked in https://github.com/influxdata/platform/issues/1833
  - [x] Teach the `tsm` engine to delete series keys based on series key prefixes. This work is tracked in #1836
  - [ ] Wire up retention enforcer to use new prefix-delete approach.
