### ISSUE TITLE
Implement meta query RPC APIs for time series data in InfluxDB

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#238]
From ifql created by [stuartcarnie](https://github.com/stuartcarnie) : influxdata/ifql#358  

The IFQL service requires APIs to service certain metadata requests. The majority of these have been identified in [MetaQueries.md](https://github.com/influxdata/ifql/blob/ff2c7283054b0368e33f32fdd48eed88bf373c3d/docs/MetaQueries.md).

Work will primarily take place in `influxd` and `ifql` to improve existing `Read` RPC.

## NOTE

The Cloud 2.0 team agreed that a working implementation should be prioritized over an optimal solution due to time pressure for UK InfluxDays.

* uses existing `Read` RPC
* serializes series frames only
* read 1 block of TSM data in order to return series for the specified time range

This is not optimal, given it is serializing all series frames for a given predicate and ifql must produce the unique set. Two options are 

* enhance the `Read` RPC API to support selecting distinct sets of tags and producing alternate frames
* introduce new, optimized APIs for querying metadata

----

- [x] `SHOW TAG KEYS FROM cpu`

    ```
    from(db:"db") 
        |> range(start:-4000h) 
        |> filter(fn:(r) => r._measurement == "cpu") 
        |> group() 
        |> keys()
    ```

- [x] `SHOW FIELD KEYS FROM cpu`

    ```
    from(db:"db") 
        |> range(start:-4000h) 
        |> filter(fn:(r) => r._measurement == "cpu") 
        |> group(by:["_field"]) 
        |> distinct(column:"_field") 
        |> group()
    ```

- [x] `SHOW TAG VALUES FROM cpu WHERE KEY = "host" LIMIT 3`

    ```
    from(db:"db") 
        |> range(start:-4000h) 
        |> filter(fn:(r) => r._measurement == "cpu") 
        |> group(by:["host"]) 
        |> distinct(column:"host") 
        |> group()
        |> limit(n:3)
    ```

- [x] `SHOW MEASUREMENTS`

    ```
    from(db:"db") 
        |> range(start:-4000h) 
        |> group(by:["_measurement"]) 
        |> distinct(column:"_measurement") 
        |> group()
    ```

**Comment by aanthony1243** [comment]
@stuartcarnie @nathanielc   is there more work on this issue?  please close if not.
