### ISSUE TITLE
Implement Functions from InfluxQL and TICKscript

### ISSUE THREAD

**Issue by adamperlin** [influxdata/platform#339]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#85  

This issue tracks progress implementing the various functions that already exist in InfluxQL or TICKscript.

If you want to own adding one of these functions, add your name next to the entry.

### Aggregations
- [x] COUNT
- [x] DISTINCT (see https://github.com/influxdata/influxdb/issues/3880 https://github.com/influxdata/influxdb/issues/3945 ) ( #231)
- [x] INTEGRAL (nc #185 )
- [x] MEAN
- [x] MEDIAN (#234)
- [ ] MODE
- [x] SPREAD (cpg: https://github.com/influxdata/ifql/pull/87)
- [x] STDDEV
- [x] SUM
### Selectors
- [x] BOTTOM (nc #229)
- [x] FIRST
- [x] LAST
- [x] MAX
- [x] MIN
- [x] PERCENTILE - This may need to have both an aggregate implementation and a selector implementation.  (See also: https://github.com/influxdata/influxdb/issues/513) (#234)
- [x] SAMPLE  (Adam)
- [x] TOP (nc #229)
### Transformations
- [ ] CEILING  (see https://github.com/influxdata/ifql/issues/266) 
- [ ] CUMULATIVE_SUM
- [x] DERIVATIVE (nc #183)
- [x] DIFFERENCE  (nc #186)
- [ ] ELAPSED
- [ ] FLOOR (see https://github.com/influxdata/ifql/issues/266)
- [ ] HISTOGRAM
- [ ] MOVING_AVERAGE
- [x] NON_NEGATIVE_DERIVATIVE - This should be rolled up into the derivative function as an argument.  (nc #183)
- [x] NON_NEGATIVE_DIFFERENCE - This should be rolled up into the difference function as an argument.  (nc #186)
### Predictors
- [ ] HOLT_WINTERS

### Functions
- [ ] Combine
- [ ] Default
- [ ] Delete
- [ ] Derivative (nc #183)
- [ ] Eval (nc  #179)
- [ ] Flatten
- [ ] From
- [x] GroupBy
- [x] Join
- [ ] NoOp
- [ ] Query
- [x] Sample
- [x] Shift (adam) https://github.com/influxdata/ifql/pull/181
- [x] StateCount (#230)
- [x] StateDuration (see https://github.com/influxdata/influxdb/issues/7342) (#230)
- [ ] Union
- [x] Where
- [ ] Window - Only fixed windows by time have been implemented. See https://github.com/influxdata/influxdb/issues/3991 for other ways to window data.

### Integration points
These should be implemented as output nodes as described in #175.

- [ ] Alert See #172 
- [ ] HTTPOut
- [ ] HTTPPost
- [ ] InfluxDBOut
- [ ] K8sAutoscale
- [ ] KapacitorLoopback
- [ ] Log
- [ ] Stats
- [ ] UDF

**Comment by nathanielc** [comment]
We should be able to write tests for all functions in this list.
